name: CI

on: [push]

jobs:

  vars:
    outputs:
      fullySupportedScalaVersions: ["2.13.6"]

  build:
    needs: vars
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        scalaVersion: ["2.13.6", "2.13.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile
        run: ./dev/make-all.sh -PscalaVersion=${{matrix.scalaVersion}}

  test:
    needs: vars
    runs-on: ubuntu-latest

    #TODO: don't repeat yourself
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        scalaVersion: ["2.13.6", "2.13.7"]

    continue-on-error: ${{ contains(needs.vars.outputs.fullySupportedScalaVersions, matrix.scalaVersion) }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #         TODO: replica! how to remove?
      - name: Test
        run: ./dev/test.sh -PscalaVersion=${{matrix.scalaVersion}}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            **/test-results/test/*.xml
          check_name: |
            Test Report (${{matrix.scalaVersion}})
